### ISSUE TITLE
error invalid access token

### ISSUE THREAD

**Issue by Hendroarifin** [Neurotech-HQ/heyoo#13]
{'error': {'message': 'Invalid OAuth access token - Cannot parse access token', 'type': 'OAuthException', 'code': 190, 'fbtrace_id':

help me please

**Comment by daudcle** [comment]
I'm also getting same error. API Key is working absolutely fine in Postman, but with python script of *heyoo* getting this error.

**Comment by Kalebu** [comment]
Hi, @daudcle @Hendroarifin  Were you able to resolve this?

**Comment by golucoder** [comment]
> Hi, @daudcle @Hendroarifin Were you able to resolve this?
> 
> This is due to the fact the `TOKEN` and `PHONE_NUMBER_ID` on your local have issues or don't really match with ones in the Facebook developer portal.
> 
> If you're using `.env` don't forget to `load_dotenv()` and also make sure you're running your script in the same directory with your `.env`, This should be able to fix it.

I am facing the same issue. Below is error. 

{'error': {'message': '(#131000) Generic error', 'type': 'OAuthException', 'code': 131000, 'error_data': {'messaging_product': 'whatsapp', 'details': 'An unknown error occurred'}, 'fbtrace_id': 'A71GMk0x3Z8ngpI1HNsz6aH'}}

PS: i am not using env variables. I am directly copy pating token and phone number id.

**Comment by Kalebu** [comment]
Hi @golucoder, What you're facing is not an Authentication issue or something to do with your ```TOKEN```, If you refer to the *[Facebook developer portal error codes](https://developers.facebook.com/docs/whatsapp/cloud-api/support/error-codes)* It is due to ```Message failed to send because of an unknown error``` which can be an issue on the WhatsApp Cloud API side, therefore,
![heyoo-issue](https://user-images.githubusercontent.com/41791983/186119135-0d7d4e56-c2fd-49d8-bd95-8b75691563f1.png)
 I suggest trying again after some time.
